title: Martins Nnamchi
description: Portfolio of Martins Nnamchi, a Full-Stack Machine Learning & Software Engineer specializing in designing, building, and deploying production-ready Python-based architectures.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
author: Martins Nnamchi
gem "github-pages", group: :jekyll_plugins
# image: https://raw.githubusercontent.com/Marrtinerz/Marrtinerz/main/portfolio-preview.jpg
url: "https://marrtinerz.github.io"
